### ISSUE TITLE
Single Channel Gateway

### ISSUE THREAD

**Issue by trlafleur** [SodaqMoja/SodaqOne-UniversalTracker#8]
Many of us are using SCG as the availability of full gateways is limited or expensive for many.

I suggest that you should conciser adding a SCG mode to your code base...

1) A switch to set SCG in the menu
2) Ability to set the Channel to use
3) Use the SF that is now in the menu

Most of the code needed for this is in your code base now... The RN driver has the code to turn off channels.

Thank

**Comment by SodaqMoja** [comment]
Sorry for the late reply.
We don't support SDG (Single  Side Gateways)
